# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\email_not_sett.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmailSettings(object):
    def setupUi(self, EmailSettings):
        EmailSettings.setObjectName("EmailSettings")
        EmailSettings.resize(335, 113)
        EmailSettings.setWindowIcon(QtGui.QIcon('icons\settings_icon.png'))
        self.gridLayout = QtWidgets.QGridLayout(EmailSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.emailOnSet = QtWidgets.QCheckBox(EmailSettings)
        self.emailOnSet.setObjectName("emailOnSet")
        self.gridLayout.addWidget(self.emailOnSet, 0, 2, 1, 1)
        self.userEmailLab = QtWidgets.QLabel(EmailSettings)
        self.userEmailLab.setObjectName("userEmailLab")
        self.gridLayout.addWidget(self.userEmailLab, 2, 1, 1, 1)
        self.userEmailSet = QtWidgets.QLineEdit(EmailSettings)
        self.userEmailSet.setObjectName("userEmailSet")
        self.gridLayout.addWidget(self.userEmailSet, 2, 2, 1, 1)
        self.emailOnLab = QtWidgets.QLabel(EmailSettings)
        self.emailOnLab.setObjectName("emailOnLab")
        self.gridLayout.addWidget(self.emailOnLab, 0, 1, 1, 1)
        self.profitLab = QtWidgets.QLabel(EmailSettings)
        self.profitLab.setObjectName("profitLab")
        self.gridLayout.addWidget(self.profitLab, 1, 1, 1, 1)
        self.profitRateSet = QtWidgets.QDoubleSpinBox(EmailSettings)
        self.profitRateSet.setObjectName("profitRateSet")
        self.gridLayout.addWidget(self.profitRateSet, 1, 2, 1, 1)
        self.saveBut = QtWidgets.QPushButton(EmailSettings)
        self.saveBut.setObjectName("saveBut")
        self.gridLayout.addWidget(self.saveBut, 3, 1, 1, 1)
        self.exitBut = QtWidgets.QPushButton(EmailSettings)
        self.exitBut.setObjectName("exitBut")
        self.gridLayout.addWidget(self.exitBut, 3, 2, 1, 1)

        self.retranslateUi(EmailSettings)
        QtCore.QMetaObject.connectSlotsByName(EmailSettings)
        

    def retranslateUi(self, EmailSettings):
        _translate = QtCore.QCoreApplication.translate
        EmailSettings.setWindowTitle(_translate("EmailSettings", "Настройки email"))
        self.emailOnSet.setText(_translate("EmailSettings", "Включено"))
        self.userEmailLab.setText(_translate("EmailSettings", "E-mail пользователя"))
        self.emailOnLab.setText(
            _translate("EmailSettings", "Включить email-уведомления")
        )
        self.profitLab.setText(
            _translate("EmailSettings", "Порог отправки сообщения,%")
        )
        self.saveBut.setText(_translate("EmailSettings", "Сохранить"))
        self.exitBut.setText(_translate("EmailSettings", "Закрыть"))
