# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(328, 288)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, 4, -1, 5)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLogging = QtWidgets.QLabel(Settings)
        self.labelLogging.setObjectName("labelLogging")
        self.gridLayout.addWidget(self.labelLogging, 0, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(Settings)
        self.saveButton.setMinimumSize(QtCore.QSize(150, 23))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 7, 0, 1, 1)
        self.WinNotSett = QtWidgets.QCheckBox(Settings)
        self.WinNotSett.setObjectName("WinNotSett")
        self.gridLayout.addWidget(self.WinNotSett, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Settings)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 3)
        self.styleLabel = QtWidgets.QLabel(Settings)
        self.styleLabel.setObjectName("styleLabel")
        self.gridLayout.addWidget(self.styleLabel, 4, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(Settings)
        self.exitButton.setMinimumSize(QtCore.QSize(150, 23))
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 7, 1, 1, 2)
        self.resourceList = QtWidgets.QLabel(Settings)
        self.resourceList.setObjectName("resourceList")
        self.gridLayout.addWidget(self.resourceList, 3, 0, 1, 1)
        self.loggingCheck = QtWidgets.QCheckBox(Settings)
        self.loggingCheck.setChecked(False)
        self.loggingCheck.setObjectName("loggingCheck")
        self.gridLayout.addWidget(self.loggingCheck, 0, 2, 1, 1)
        self.settReqFreq = QtWidgets.QSpinBox(Settings)
        self.settReqFreq.setObjectName("settReqFreq")
        self.gridLayout.addWidget(self.settReqFreq, 2, 2, 1, 1)
        self.styleSett = QtWidgets.QComboBox(Settings)
        self.styleSett.setEditable(False)
        self.styleSett.setCurrentText("")
        self.styleSett.setMaxVisibleItems(100)
        self.styleSett.setPlaceholderText("")
        self.styleSett.setDuplicatesEnabled(False)
        self.styleSett.setFrame(False)
        self.styleSett.setObjectName("styleSett")
        self.gridLayout.addWidget(self.styleSett, 4, 2, 1, 1)
        self.labelReqFreq = QtWidgets.QLabel(Settings)
        self.labelReqFreq.setObjectName("labelReqFreq")
        self.gridLayout.addWidget(self.labelReqFreq, 2, 0, 1, 1)
        self.labelnWinNot = QtWidgets.QLabel(Settings)
        self.labelnWinNot.setObjectName("labelnWinNot")
        self.gridLayout.addWidget(self.labelnWinNot, 1, 0, 1, 1)
        self.resourceSett = QtWidgets.QListWidget(Settings)
        self.resourceSett.setObjectName("resourceSett")
        self.gridLayout.addWidget(self.resourceSett, 3, 2, 1, 1)
        self.phemexLab = QtWidgets.QLabel(Settings)
        self.phemexLab.setObjectName("phemexLab")
        self.gridLayout.addWidget(self.phemexLab, 5, 0, 1, 1)
        self.phemexAuthTok = QtWidgets.QLineEdit(Settings)
        self.phemexAuthTok.setObjectName("phemexAuthTok")
        self.gridLayout.addWidget(self.phemexAuthTok, 5, 2, 1, 1)

        self.retranslateUi(Settings)
        self.styleSett.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Settings)

        # custom code
        self.resourceSett.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        Settings.setWindowIcon(QtGui.QIcon('icons\settings_icon.png'))

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.labelLogging.setText(_translate("Settings", "Включить логирование"))
        self.saveButton.setText(_translate("Settings", "Сохранить"))
        self.WinNotSett.setText(_translate("Settings", "Включено"))
        self.label.setText(
            _translate("Settings", "Изменение стиля требует перезапуска приложения")
        )
        self.styleLabel.setText(_translate("Settings", "Стиль приложения"))
        self.exitButton.setText(_translate("Settings", "Закрыть"))
        self.resourceList.setText(_translate("Settings", "Список источников"))
        self.loggingCheck.setText(_translate("Settings", "Включено"))
        self.labelReqFreq.setText(_translate("Settings", "Частота запросов, секунд"))
        self.labelnWinNot.setText(_translate("Settings", "Включить уведомления"))
        self.phemexLab.setText(_translate("Settings", "Phemex auth-token"))
